# specify base image that we want to extend
FROM kartoza/postgis:12.1

# set environment variables that we want to change
ENV POSTGRES_DBNAME="gis"
ENV POSTGRES_USER="testuser"
ENV POSTGRES_PASS="testpw"

